// Small deterministic content build. No network, secrets, packages, or runtime HTML rendering.
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { ARTICLE_TYPES, TEMPLATES, EXAMPLES } from '../public/content-data.js';
import { createMarkdown } from '../public/markdown.js';
const esc = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const a = (href, text, cls = '') => `<a href="${href}"${cls ? ` class="${cls}"` : ''}>${text}</a>`;
const li = items => `<ul>${items.map(item => `<li>${item}</li>`).join('')}</ul>`;
const notice = text => `<aside class="notice">${text}</aside>`;
const steps = items => `<ol class="task-steps">${items.map(([title, text]) => `<li><h2>${title}</h2><p>${text}</p></li>`).join('')}</ol>`;
const cards = items => `<div class="resource-grid">${items.map(([title, text, link, action]) => `<article class="paper"><h2>${title}</h2><p>${text}</p>${a(link, action)}</article>`).join('')}</div>`;
const status = '<strong>In development.</strong> Public examples, templates, and the sample editor need no account. AI generation is restricted to the owner and invited testers, and requires private setup. Nothing is published automatically.';
const pages = new Map();
function add(path, title, description, body, { script = false, wide = false } = {}) {
  const nav = [['/examples/', 'Examples'], ['/templates/', 'Templates'], ['/help/', 'Help'], ['/pilot', 'Pilot sign-in']].map(([url, label]) => `<a href="${url}"${url === path ? ' aria-current="page"' : ''}>${label}</a>`).join('');
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} | Draft to Page</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#244b40">
<link rel="canonical" href="https://drafttopage.com${path}"><meta property="og:title" content="${esc(title)} | Draft to Page"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="https://drafttopage.com${path}">
<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/pilot.css"><link rel="stylesheet" href="/content.css">${path === '/404.html' ? '<meta name="robots" content="noindex">' : ''}</head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header wrap"><a class="brand" href="/">Draft to Page<span aria-hidden="true">.</span></a><nav aria-label="Main navigation">${nav}</nav></header>
<main id="main" class="${path === '/' ? '' : `wrap content-main${wide ? ' wide' : ''}`}" data-release="content-pilot-20261008">${body}</main>
<footer class="site-footer wrap"><div><a class="brand" href="/">Draft to Page.</a><p>Your ideas. Your voice. Your approval.</p></div><nav aria-label="Footer navigation">${a('/getting-started/', 'Getting started')}${a('/access/', 'Access & status')}${a('/privacy/', 'Data use')}</nav><span class="badge">In development</span></footer>
${script ? '<script type="module" src="/resources.js"></script>' : ''}</body></html>\n`;
  pages.set(path, html);
}
const heading = (label, title, intro) => `<header class="page-intro"><p class="eyebrow">${label}</p><h1>${title}</h1><p class="lead">${intro}</p></header>`;
add('/', 'Your notes, shaped into your next website article', 'Turn your own notes into a short, reviewable website article. Explore examples, copy note templates, and try a sample Markdown export.', `
<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">For independent website owners</p><h1>Your notes.<br>Your next page.</h1><p class="lead">Turn what you already know into a clear article you can edit and export.</p><p>Bring your ideas, facts, and observations. Draft to Page helps shape a short article, title, summary, and page description. You check the claims and keep the final say.</p><div class="actions">${a('/demo/', 'Try the sample editor', 'button')}${a('/examples/', 'See complete examples', 'text-link')}</div><p class="small">The sample editor uses prewritten fictional material, not live AI. ${a('/pilot', 'Invited already? Open the pilot.')}</p></div>
<aside class="outline"><p class="eyebrow">What you take away</p><p class="outline-title">An article.<br>And the details around it.</p><ol class="package-list"><li><span>01</span><div><strong>Your editable writing</strong><p>A title, article, short excerpt, and page description.</p></div></li><li><span>02</span><div><strong>Questions to resolve</strong><p>Suggested review questions, not a complete fact-check.</p></div></li><li><span>03</span><div><strong>A Markdown file</strong><p>Download or copy, then review in your own publishing workflow.</p></div></li></ol><p class="small">No automatic publishing. No independent research. No invented life story.</p></aside></section>
<section class="section wrap" id="process"><p class="eyebrow">A focused workflow</p><h2>Bring the substance.<br>Keep the final say.</h2><div class="workflow"><article><p class="step-number">01 / Notes</p><h3>Start with what is true.</h3><p>Use your own material. Mark uncertainty instead of asking the tool to fill factual gaps.</p>${a('/templates/', 'Choose a note outline')}</article><article><p class="step-number">02 / Draft</p><h3>Choose an article type.</h3><p>Personal essay, project update, or practical guide. Built-in presets, not a learned personal voice.</p></article><article><p class="step-number">03 / Review</p><h3>Make it yours.</h3><p>Edit the wording. Check facts, permissions, and any unanswered questions.</p>${a('/guides/review/', 'Use the review checklist')}</article><article><p class="step-number">04 / Export</p><h3>Take the next step.</h3><p>Save Markdown and preview it in your website workflow. An export is not a published page.</p>${a('/help/markdown-export/', 'Understand the file')}</article></div></section>
<section class="example-band" id="example"><div class="wrap section"><p class="eyebrow">Three useful starting points</p><h2>Less blank page.<br>More of your thinking.</h2>${cards(EXAMPLES.map(e => [ARTICLE_TYPES[e.profile], esc(e.label) + '. See the notes, article, metadata, and unresolved questions.', `/examples/#${e.id}`, 'See the complete example']))}</div></section>
<section class="section wrap status" id="status"><div><p class="eyebrow">Small on purpose</p><h2>A useful workflow before a bigger product.</h2></div><div><p>${status}</p><p>No public registration, billing, direct website integration, saved personal profiles, or draft history is included.</p><p>${a('/access/', 'Read about access and activation')} · ${a('/privacy/', 'Understand the data flow')}</p></div></section>`, { wide: true });

add('/templates/', 'Note templates', 'Six copyable note outlines for personal essays, project updates, and practical guides. Prepare source material without inventing missing facts.', `${heading('Start with your material', 'A better starting point than a blank box.', 'Choose an outline, fill it in using your own facts, and mark what you do not know. These templates work with or without pilot access.')}
${notice('Copying an outline does not send it to AI or open a session. Keep a copy in your own document. Do not put private notes in a URL or a public GitHub issue.')}
<nav class="jump-links" aria-label="Choose a template">${TEMPLATES.map(t => a(`#${t.id}`, t.title)).join('')}</nav><p id="resource-status" class="message" role="status" aria-live="polite"></p>
<div class="template-grid">${TEMPLATES.map(t => `<article class="paper template" id="${t.id}"><p class="eyebrow">${ARTICLE_TYPES[t.profile]}</p><h2>${t.title}</h2><p>${t.purpose}</p><label for="outline-${t.id}">Copyable outline</label><textarea id="outline-${t.id}" rows="8" readonly>${esc(t.outline)}</textarea><button type="button" class="secondary" data-copy="outline-${t.id}">Copy ${t.title.toLowerCase()} outline</button><details><summary>Fictional filled example</summary><p>${esc(t.example)}</p></details><p class="small"><strong>Keep this boundary:</strong> ${t.caution}</p><p>${a('/pilot', 'Open the private pilot')} and choose <strong>${ARTICLE_TYPES[t.profile]}</strong>.</p></article>`).join('')}</div><noscript><p>JavaScript is off. Select the visible outline text and copy it manually.</p></noscript><p>${a('/guides/source-notes/', 'Learn how to prepare stronger source notes')} or ${a('/demo/', 'try the sample editor')}.</p>`, { script: true, wide: true });

function sampleBody(body) {
  return body.split('\n\n').map(block => block.startsWith('## ') ? `<h4>${esc(block.slice(3))}</h4>` : /^1\. /.test(block) ? `<ol>${block.split('\n').map(line => `<li>${esc(line.replace(/^\d+\. /, ''))}</li>`).join('')}</ol>` : `<p>${esc(block)}</p>`).join('');
}
add('/examples/', 'Complete article examples', 'Compare source notes with three fictional article packages, including page details, review questions, and downloadable sample Markdown.', `${heading('Illustrative examples', 'See the whole package, not just the prose.', 'Each example below was written to explain the workflow. None is a live model response, customer result, or verified personal experience.')}
<nav class="jump-links" aria-label="Choose an example">${EXAMPLES.map(e => a(`#${e.id}`, e.label)).join('')}</nav>
${EXAMPLES.map(e => `<section id="${e.id}" class="example-section"><p class="eyebrow">Illustrative example / ${ARTICLE_TYPES[e.profile]}</p><h2>${e.label}</h2><div class="example-grid"><article class="paper source"><h3>The supplied notes</h3><p>${esc(e.notes)}</p><dl><dt>Audience</dt><dd>${esc(e.audience)}</dd><dt>Purpose</dt><dd>${esc(e.purpose)}</dd></dl></article><article class="paper sample-article"><p class="eyebrow">A possible article</p><h3>${esc(e.draft.title)}</h3>${sampleBody(e.draft.body)}</article></div><div class="example-grid"><article class="paper"><h3>The page details</h3><dl><dt>Excerpt</dt><dd>${esc(e.draft.excerpt)}</dd><dt>Page description</dt><dd>${esc(e.draft.description)}</dd><dt>Filename</dt><dd><code>${e.draft.slug}.md</code></dd></dl>${a(`/samples/${e.id}.md`, 'Open sample Markdown')} · <a href="/samples/${e.id}.md" download="${e.draft.slug}.md">Download sample</a></article><article class="paper"><h3>What needs a human decision</h3><p>${esc(e.decision)}</p>${li(e.draft.questions.map(esc))}<p class="small">These are teaching questions, not evidence that an independent fact-check occurred.</p></article></div></section>`).join('')}
${notice('Sample downloads contain fictional article text and metadata, but not source notes or review questions. Do not present a fictional first-person example as your own experience.')}
<div class="actions">${a('/demo/', 'Edit a sample yourself', 'button')}${a('/templates/', 'Prepare your own notes')}${a('/help/markdown-export/', 'Read the export guide')}</div>`, { wide: true });

add('/demo/', 'Try the sample editor', 'Edit a prewritten fictional article, review it, and export Markdown in your browser. No account and no live AI generation.', `${heading('Public sample editor', 'Try editing and exporting a page.', 'This editor loads prewritten fictional examples. It does not generate writing, call an AI service, or publish anything.')}
${notice('<strong>No autosave.</strong> Edits stay in this open page and can be lost when you refresh or leave. Download what you want to keep. Do not enter sensitive material.')}
<div id="demo"><div class="paper"><label for="demo-example">Choose a prewritten example</label><select id="demo-example">${EXAMPLES.map(e => `<option value="${e.id}">${e.label}</option>`).join('')}</select><button id="demo-load" class="secondary" type="button">Load selected sample</button></div><p id="resource-status" class="message" role="status" aria-live="polite"></p><div class="workspace"><section class="pilot-card"><h2>The fictional source</h2><p id="demo-notes"></p><h3>Questions to check</h3><ul id="demo-questions"></ul><p class="small">This is an editorial demonstration, not a model-quality test. Select a sample above, then edit the article fields. Changing a field clears approval.</p>${a('/examples/', 'Read all complete examples')}</section><section class="pilot-card"><h2>Your editable sample</h2><label for="demo-title">Article title</label><input id="demo-title" maxlength="160"><label for="demo-excerpt">Short excerpt</label><textarea id="demo-excerpt" rows="3" maxlength="300"></textarea><label for="demo-description">Page description</label><textarea id="demo-description" rows="3" maxlength="160"></textarea><label for="demo-slug">Filename, without .md</label><input id="demo-slug" maxlength="80" spellcheck="false"><label for="demo-body">Article body, in Markdown</label><textarea id="demo-body" rows="16" maxlength="12000"></textarea><label class="check"><input id="demo-reviewed" type="checkbox"><span>I have reviewed this sample and understand that exporting does not publish it.</span></label><div class="actions"><button id="demo-download" type="button" class="button" disabled>Download Markdown</button><button id="demo-copy" type="button" class="secondary" disabled>Copy Markdown</button></div><p class="small">The file includes <code>draft: true</code>, not a universal publication lock. Notes and review questions are omitted. ${a('/help/markdown-export/', 'What to do with your export')}</p></section></div></div><noscript><p>The editor needs JavaScript. ${a('/examples/', 'Read the examples and download the same sample files without JavaScript.')} No AI access is required.</p></noscript>`, { script: true, wide: true });

add('/getting-started/', 'Getting started', 'A first-use guide to preparing notes, using the invitation-only pilot, reviewing an article, and exporting Markdown.', `${heading('First-use guide', 'From your notes to a reviewed export.', 'Start with one short article and material you are comfortable sending to the AI provider. No pilot access yet? The sample editor lets you practice editing and exporting.')}
${notice('Keep your original notes in your own document. The pilot has no autosave, draft history, or recovery service. Article exports omit your notes and review questions.')}
${steps([
['Choose one job', 'Pick Personal essay for a supplied experience, Project update for completed work and plans, or Practical guide for a process you know. These are article types, not custom website profiles or learned voices.'],
['Prepare the source', 'Use a '+a('/templates/', 'note template')+'. Separate facts from interpretation and uncertainty. The pilot accepts 30 to 8,000 characters. A short specific note is better than a long request to invent material.'],
['Open the private pilot', 'Use the invitation password from the owner. There is no public registration or password recovery. The password is not an API key. When the pilot is unavailable, return to the public resources or contact the person who invited you.'],
['Set the audience and purpose', 'Audience describes who will read the page. Purpose describes what the page should help them understand. Both are optional, but specific answers help you judge the draft.'],
['Review the data-use notice', 'Confirm that you have permission to use the material. Preparing a draft sends the notes, article-type guidance, audience, and purpose through the backend to Anthropic. '+a('/privacy/', 'Read the full data-use notice')+' before agreeing.'],
['Prepare one draft', 'Select Prepare draft once. Failed attempts count toward the shared limit; the app does not automatically retry. Keep this tab open. There are 20 shared attempts per UTC day, at least 30 seconds apart.'],
['Edit the writing and page details', 'The title names the page. The excerpt is a short introduction or listing summary. The page description describes the page for your publishing system. The filename uses lowercase letters, numbers, and hyphens. The article body uses Markdown. No field guarantees a particular search appearance.'],
['Resolve the review questions', 'Check names, dates, claims, links, permissions, and whether the writing sounds like you. Missing questions do not mean the draft is verified. '+a('/guides/review/', 'Use the review checklist')+'. Save unresolved questions separately.'],
['Approve and export', 'Check the review box, then download or copy Markdown. Editing any article field clears approval. Read '+a('/help/markdown-export/', 'the export guide')+' before moving the file into your website workflow. Nothing is published by this action.']
])}<div class="actions">${a('/pilot', 'Open the private pilot', 'button')}${a('/demo/', 'Practice with a sample')}</div>`);

add('/help/markdown-export/', 'Understand your Markdown export', 'Learn what the exported Markdown contains, how to handle metadata and headings, and how to preview it safely before publishing.', `${heading('Export guide', 'A file to review, not a published page.', 'Markdown is plain text with simple formatting markers. Draft to Page packages your article with page details so you can take it into your own publishing workflow.')}
${notice('<code>draft: true</code> is metadata. It only prevents publication when the destination is configured to honor it. It is not an access control or a universal safety lock.')}
<h2>What the file contains</h2><pre class="code-sample"><code>---\ntitle: "Your article title"\nexcerpt: "A short introduction"\ndescription: "A page description"\ndraft: true\n---\n\n# Your article title\n\nYour reviewed article body.</code></pre><p>The filename comes from the filename field in the editor. Source notes and review questions are deliberately excluded. Copy those separately into your own private document when needed.</p>
<h2>Review the handoff before changing a website</h2>${li([
'Open the file in a trusted text editor first. Confirm that your edits are present and that the article is complete.',
'Treat the exported text as untrusted input. Review links, HTML-like text, and markup before using a renderer. The pilot does not sanitize output for every platform.',
'Check how your destination handles the metadata block between the lines of three hyphens. Some workflows use those fields; others need them entered separately.',
'Check the title. The export includes both a metadata title and a body heading. A website that generates its own title may display it twice.',
'Preview on desktop and mobile in a nonpublic environment before publishing. Check headings, paragraph breaks, lists, links, and any images you add.'
])}<h2>A manual GitHub workflow to validate</h2><p>This is a checklist for a Markdown-based website, not a verified integration with your particular repository.</p><ol><li>Confirm the repository expects Markdown and identify the correct content directory and metadata format.</li><li>Keep private notes and unpublished sensitive content out of public repositories. A feature branch in a public repository is still public.</li><li>On a feature branch, adapt a non-sensitive article file to the destination's requirements. Check whether it expects a date, layout, slug, or other fields that this export does not supply.</li><li>Run the destination's build and inspect its preview. Confirm whether the draft flag is honored and whether the title appears once.</li><li>Review the change before merging. Merging may trigger publication in the destination, even though exporting here does not.</li></ol>
<h2>Using another publishing system</h2><p>No direct WordPress, Squarespace, Ghost, or other website integration is included. You may need to paste the article body into an editor, apply formatting, and enter the title, excerpt, and description separately. Do not assume uploading this file is supported.</p><h2>A successful final check</h2><p>You should be able to find your edited title and sentence in the actual downloaded file, explain where each field belongs in the destination, and preview the result without publishing it by accident.</p><p>${a('/samples/studio.md', 'Open a sample export')} · ${a('/demo/', 'Practice with the sample editor')} · ${a('/help/', 'Troubleshooting')}</p>`);

const faqs = [
['Who can use the pilot?', 'The owner and invited testers only. Public examples, templates, and the sample editor need no account. There is no public registration, billing, or per-user password recovery.'],
['Why does the pilot say it is not activated?', 'Private access or usage protection has not been configured successfully. The public resources remain available. The owner should follow the activation checklist; an invited tester should contact the person who invited them.'],
['What does the sample editor do?', 'It loads prewritten fictional articles that you can edit and export in this browser tab. It does not call AI or demonstrate actual model quality.'],
['What does Article type change?', 'It selects one of three built-in writing presets. It does not learn your voice, save a custom website profile, or add facts to the notes.'],
['Does the tool research or fact-check?', 'No. The pilot asks the model to use supplied facts and identify open questions. Those instructions are not a guarantee of correctness. The model can still misstate or invent information.'],
['Why is generation unavailable after sign-in?', 'The AI credential may be missing, or a connection check may have failed. Use Recheck connection without refreshing your working tab. An authentication, billing, or provider-access problem requires the owner to inspect the private configuration.'],
['What happens when an attempt fails?', 'Your existing notes and draft stay in the open page. There is no automatic retry. Failed provider attempts count toward the shared limit. Review the error and deliberately decide whether to try again.'],
['How do shared limits work?', 'The whole pilot shares 20 reserved generation attempts per UTC day, at least 30 seconds apart. Failed provider attempts count. Signing out or using another browser does not reset the counters. The daily window resets at midnight UTC.'],
['Why can I not export yet?', 'Check the review box. Editing any article field clears that approval. The filename must contain lowercase letters, numbers, and separating hyphens; title, excerpt, description, and body must not be empty.'],
['My session ended. How do I keep the draft?', 'Leave the working tab open. Follow the sign-in link in a new tab, sign in there, then return and select Recheck connection. Do not refresh the working tab: there is no autosave.'],
['The clipboard did not work. What now?', 'For template outlines, select and copy the visible text manually. For articles, use Download Markdown. Check that a real file arrived on your device before closing the workspace.'],
['Can I recover work after leaving?', 'There is no recovery service or saved history. Keep original notes in your own document and download the reviewed article before leaving. Browser navigation can discard unsaved work.'],
['Where do my notes go?', 'In the private pilot, the source notes, selected article-type guidance, audience, and purpose go through Cloudflare to Anthropic when you select Prepare draft. Read the data-use notice. Public template copies and sample-editor edits do not call AI.'],
['Where do I report a problem?', 'Invited testers should use the direct contact route agreed with the owner. Do not paste passwords, API keys, private notes, or draft content into a public issue. Include the operation, approximate time, browser, and visible error without private material.']
];
add('/help/', 'Help and troubleshooting', 'Practical answers about pilot access, note preparation, review, export, shared limits, and preserving work when a session expires.', `${heading('Help', 'Finish the task without guessing.', 'Start with the first-use guide, check the export format, or find the error you are seeing below.')}${cards([['First article', 'Prepare notes and complete a reviewed export.', '/getting-started/', 'Follow the first-use guide'], ['Your exported file', 'Understand metadata, headings, and the publishing handoff.', '/help/markdown-export/', 'Read the export guide'], ['Access and status', 'Understand the public resources and invitation-only pilot.', '/access/', 'Check the access guidance']])}<section class="faq"><h2>Practical questions</h2>${faqs.map(([q, answer]) => `<details><summary>${q}</summary><p>${answer}</p></details>`).join('')}</section><p>${a('/privacy/', 'Read the complete data-use notice')} before submitting notes.</p>`, { wide: true });

add('/access/', 'Pilot access and activation', 'Understand what is public, what requires an invitation, and what the owner must verify before activating real AI generation.', `${heading('Access & status', 'Public resources. A private pilot.', 'Use the learning resources now. Live AI generation remains a small invitation-only test, not a public service.')}${notice(status)}
<h2>Available without signing in</h2><p>${a('/examples/', 'Complete fictional examples')}, ${a('/templates/', 'six note templates')}, ${a('/demo/', 'an editable sample workspace')}, and ${a('/help/', 'practical help')}. These resources do not require a provider account and do not send your writing to AI.</p><h2>Already invited?</h2><p>${a('/pilot', 'Open the private pilot')} and use the password supplied through the owner's agreed private channel. There are no individual accounts or password-reset emails. When access is unavailable, contact the person who invited you rather than submitting credentials elsewhere.</p><h2>Not invited yet?</h2><p>Public applications are not open. There is no waiting-list form or automatic invitation process. Use the public resources to see whether the workflow fits your needs.</p><h2>Owner activation checklist</h2><p>This page does not inspect account settings or verify whether the AI provider is ready. The actual pilot page reports whether sign-in is available; the authenticated workspace reports generation configuration.</p><ol><li>Confirm the latest deployment succeeded for the existing Cloudflare Worker <code>drafttopage</code> and that its quota binding is present.</li><li>Configure the private pilot password and project-specific AI credential as runtime secrets, never in this public repository, browser scripts, or chat.</li><li>Set a small provider spending limit and review provider data handling before making a real request.</li><li>Use fictional notes for one owner-only generation test. Edit the result, approve it, download the actual file, and check that the edits are included.</li><li>Verify sign-out and anonymous access blocking. Confirm the provider usage and establish a direct support route before inviting testers.</li></ol><p>The full repository checklist is in <code>docs/ACTIVATION_CHECKLIST.md</code>. No access or spending limit should be bypassed to make the app appear available.</p><p>${a('/privacy/', 'Read the data-use notice')} · ${a('/getting-started/', 'Prepare for your first article')}</p>`);

add('/guides/source-notes/', 'Prepare useful source notes', 'Separate facts, interpretation, uncertainty, audience, and purpose before turning your material into a draft.', `${heading('Writing guide', 'Give the draft something real to work with.', 'The useful input is your substance, not a clever instruction to manufacture authority.')}
<h2>Start with one article-sized question</h2><p>Choose the single thing this page should explain. A short update about what you finished is easier to review than a request to summarize everything about a project.</p><h2>Separate three kinds of statement</h2><dl><dt>Observed or documented</dt><dd>What happened, what you did, or what a source actually establishes.</dd><dt>Interpretation</dt><dd>What you think it means. Make it clear that this is your reading of the situation.</dd><dt>Unresolved</dt><dd>What is uncertain, unconfirmed, or missing. Leave it as a question rather than filling the gap.</dd></dl><h2>Compare two possible inputs</h2><div class="paper"><p><strong>Too vague:</strong> Write an inspiring update about how our project is transforming the neighborhood.</p><p><strong>More reviewable, fictional input:</strong> Two volunteers checked a suggested reading list. We have not confirmed meeting dates or a venue. Explain the progress without implying that a meeting is scheduled.</p></div><h2>Include the audience and purpose</h2><p>“Neighbors considering a reading group” gives you a clearer editing target than “everyone.” “Explain what is complete and what remains undecided” is more specific than “make it engaging.”</p><h2>Remove material that should not be submitted</h2><p>Do not paste credentials, sensitive personal information, confidential business material, or someone else's writing without permission. Keep your full original notes in your own document and submit only what is needed.</p><h2>Stop when the notes are too thin</h2><p>The pilot is not a research service. When the important facts are missing, gather them first or publish a smaller claim. A shorter accurate piece is preferable to a padded article with invented substance.</p><p>${a('/templates/', 'Choose a copyable note template')} · ${a('/guides/review/', 'Review the eventual draft')}</p>`);

add('/guides/review/', 'Review an AI-assisted draft', 'A practical pre-publication checklist for factual claims, voice, uncertainty, permissions, metadata, and the publishing handoff.', `${heading('Review checklist', 'Approval is an editorial decision.', 'A smooth sentence can still be wrong. Read for claims and meaning before polishing the wording.')}
${steps([
['Compare the draft with your source', 'Look for names, dates, quotations, numbers, achievements, causal claims, and promises that were not supplied. Delete them or verify them independently. Do not assume they are true because the draft sounds confident.'],
['Preserve uncertainty', 'A test is not a proven result. A plan is not completed work. A personal interpretation is not an established fact. Check that the draft has not quietly erased those distinctions.'],
['Make the voice specific', 'Read the piece aloud. Replace vague enthusiasm and language you would not use. Add a concrete detail only when it is real and you have permission to share it.'],
['Check permissions and consequences', 'Confirm that quotations, personal stories, images, and identifying details can be published. Do not use this checklist as a substitute for professional review of high-stakes material.'],
['Resolve the open questions', 'The suggested questions may be incomplete. Answer them using your own knowledge or reliable sources. Save remaining questions outside the article export. A draft with no returned questions is not automatically verified.'],
['Check the complete package', 'Review title, excerpt, description, filename, and body together. The summary should not make a stronger claim than the article. Check the actual downloaded file and preview the destination before publishing.']
])}${notice('The review checkbox records your action in the current page. It is not a certificate of accuracy, an independent audit, or a permanent approval record.')}
<p>${a('/demo/', 'Practice reviewing a sample')} · ${a('/help/markdown-export/', 'Check the export handoff')}</p>`);

add('/privacy/', 'Data use', 'How public resources and the private pilot handle writing, sign-in, usage limits, unsaved work, and exports.', `${heading('Data use', 'Your writing, and where it goes.', 'Draft to Page is in development. The private pilot is an invitation-only test, not a public publishing service.')}
${notice('Do not submit sensitive personal data, confidential business information, passwords, or material you lack permission to use.')}
<h2>Public resources and the sample editor</h2><p>The examples and templates are public, fictional teaching material. Copying an outline and editing or exporting a prewritten sample do not call an AI service. Sample-editor edits stay in the open page; application code does not save them to browser storage or a server database. Refreshing or leaving can discard them. Hosting-provider operational processing is separate.</p><h2>When you generate a private-pilot draft</h2><p>Your notes, selected article-type guidance, audience, and purpose pass through the Cloudflare-hosted backend and are sent to Anthropic's Claude API. The response returns to your browser. The application does not browse for more information or publish anything.</p><p>Application code does not save notes or draft content to a server database, browser persistent storage, or application logs. That is not a promise of zero retention by infrastructure providers. Cloudflare and Anthropic process requests under their applicable policies, agreements, and account settings. Review those terms before using private material.</p><h2>Sign-in and usage protection</h2><p>A Secure, HttpOnly, SameSite sign-in cookie lasts up to four hours. Signing out removes it from that browser. Rotating the shared password invalidates sessions. There are no separate customer accounts or individual password-recovery features.</p><p>A Cloudflare Durable Object stores shared sign-in and generation counters and timestamps, not notes or drafts. The whole pilot shares 20 reserved generation attempts per UTC day, at least 30 seconds apart. Failed provider attempts count. Application code includes no analytics or advertising scripts.</p><h2>Unsaved writing and exports</h2><p>The editor keeps writing in the open page. Refreshing, leaving, clearing, or signing out can discard it. There is no draft history, autosave, or recovery service. Clipboard copies and downloaded files are handled by your device and are outside the application's control.</p><p>Article exports include metadata and a draft flag. They omit source notes and review questions. Save those separately in your own private document. Review Markdown, links, and markup in a safe editor before publishing. The pilot does not guarantee factual accuracy or sanitize output for every publishing platform.</p><h2>Questions and pilot participation</h2><p>Before inviting testers, the owner must verify provider settings and spending controls, explain the shared-password arrangement, and establish a direct contact route. Invited testers should use that agreed route for access or data-use questions. No public sign-up, payment collection, or marketing mailing list is enabled.</p><p><a href="https://privacy.anthropic.com/" rel="noreferrer">Anthropic privacy information</a> · <a href="https://www.cloudflare.com/privacypolicy/" rel="noreferrer">Cloudflare privacy policy</a></p><p>${a('/access/', 'Access and activation')} · ${a('/help/', 'Practical help')}</p>`);

add('/404.html', 'Page not found', 'Find Draft to Page examples, templates, practical help, and private-pilot access.', `${heading('Page not found', 'That page is not here.', 'The address may have changed. Your next step is still available.')}${cards([['Try a sample', 'Edit and export prewritten fictional material without signing in.', '/demo/', 'Open the sample editor'], ['Prepare your notes', 'Choose one of six copyable outlines.', '/templates/', 'Browse templates'], ['Get help', 'Find access, review, and export guidance.', '/help/', 'Open help']])}`, { wide: true });

for (const [path, html] of pages) {
  const file = path === '/404.html' ? 'public/404.html' : `public${path}index.html`;
  await mkdir(dirname(file), { recursive: true }); await writeFile(file, html);
}
await mkdir('public/samples', { recursive: true });
for (const example of EXAMPLES) await writeFile(`public/samples/${example.id}.md`, createMarkdown(example.draft));
const indexable = [...pages.keys()].filter(path => path !== '/404.html');
await writeFile('public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${indexable.map(path => `  <url><loc>https://drafttopage.com${path}</loc></url>`).join('\n')}\n</urlset>\n`);
await writeFile('public/robots.txt', 'User-agent: *\nDisallow: /pilot\nDisallow: /api/\nSitemap: https://drafttopage.com/sitemap.xml\n');
await writeFile('public/release.json', JSON.stringify({ release: 'content-pilot-20261008', publicPages: indexable.length, exampleType: 'illustrative', publicAIGeneration: false }) + '\n');
console.log(`Built ${pages.size} public HTML pages and ${EXAMPLES.length} sample exports from public-safe source.`);
