import { RECOVERY_HTML } from '../src/recovery-markup.js';
export const writingPages = [
  {
    route: '/write/', title: 'Local writing desk', description: 'Write or edit your own article without AI, preview basic Markdown, and save a private workspace file to resume later.',
    body: `<header class="page-intro"><p class="eyebrow">Local writing desk / No AI</p><h1>Your own words. A useful place to finish them.</h1><p class="lead">Paste an existing article or write here. Add page details, review, and export. No invitation or AI activation is needed.</p></header>
<p class="desk-note"><strong>You do the writing.</strong> This page does not generate text, send your writing to AI, or upload it. Edits stay in this open tab. <strong>No autosave:</strong> download a private backup to keep unfinished work.</p>
<p><a href="/demo/" target="_blank" rel="noopener">Try a fictional sample (new tab)</a> · <a href="/templates/" target="_blank" rel="noopener">Open note templates (new tab)</a> · <a href="/help/local-workspace/" target="_blank" rel="noopener">Writing-desk help (new tab)</a></p>
<noscript><p>The writing desk needs JavaScript. You can still read <a href="/examples/">the examples</a> and copy <a href="/templates/">note outlines</a>. No writing is submitted by this page.</p></noscript>
<p id="desk-status" class="message" role="status" aria-live="polite" aria-atomic="true"></p>
${RECOVERY_HTML}
<div class="desk-columns"><section class="paper" aria-labelledby="article-heading"><h2 id="article-heading">Your article</h2>
<label for="title">Article title</label><input id="title" maxlength="160" autocomplete="off">
<label for="excerpt">Short excerpt</label><textarea id="excerpt" rows="3" maxlength="300" aria-describedby="excerpt-help"></textarea><p id="excerpt-help" class="small">An introduction or listing summary, up to 300 characters.</p>
<label for="description">Page description</label><textarea id="description" rows="3" maxlength="160" aria-describedby="description-count"></textarea><p id="description-count" class="small">0 / 160 characters</p>
<label for="slug">Filename, without .md</label><input id="slug" maxlength="80" spellcheck="false" autocomplete="off" aria-describedby="slug-help"><p id="slug-help" class="small">Use lowercase letters, numbers, and separating hyphens.</p><button id="suggest-slug" type="button" class="secondary">Suggest filename from title</button>
<label for="body">Article body, in Markdown</label><textarea id="body" rows="20" maxlength="12000" aria-describedby="body-count"></textarea><p id="body-count" class="small">0 approximate words; 0 / 12,000 characters</p>
<details id="preview-panel"><summary>Show basic reading preview</summary><p class="small">Paragraphs, standalone headings, and simple lists only. Links, images, inline formatting, and HTML are shown as text, not loaded or executed. Preview your actual publishing system separately.</p><div id="article-preview" class="article-preview"></div></details>
<label class="check"><input id="reviewed" type="checkbox"><span>I have reviewed the article and understand that exporting does not publish it.</span></label>
<div class="actions"><button id="download" type="button" class="button" disabled>Download Markdown</button><button id="copy" type="button" class="secondary" disabled>Copy Markdown</button><button id="copy-body" type="button" class="secondary" disabled>Copy article body</button></div>
<p class="small">Complete all article fields before export. Editing any field clears approval. Article exports omit source notes and review questions. <code>draft: true</code> is not a universal publication lock.</p><p><a href="/help/markdown-export/" target="_blank" rel="noopener">What to do with the exported file (new tab)</a></p>
</section><aside class="paper" aria-labelledby="source-heading"><h2 id="source-heading">Notes and review</h2><p>Optional planning fields stay separate from the article. They are included in a private backup, not in an article export.</p>
<label for="profile">Article type</label><select id="profile" aria-describedby="profile-help"><option value="personal">Personal essay</option><option value="update">Project update</option><option value="guide">Practical guide</option></select><p id="profile-help" class="small">An organizing label here. Selecting it does not generate or rewrite anything.</p>
<label for="audience">Audience, optional</label><input id="audience" maxlength="160" autocomplete="off"><label for="purpose">Purpose, optional</label><input id="purpose" maxlength="240" autocomplete="off"><label for="notes">Source notes, optional</label><textarea id="notes" rows="10" maxlength="8000" aria-describedby="note-count"></textarea><p id="note-count" class="small">0 / 8,000 characters</p>
<section id="imported-questions" hidden><h3>Questions from the restored workspace</h3><ul id="questions"></ul><p class="small">These questions may be incomplete. Restoring them does not verify their claims.</p></section>
<h3>Before you export</h3><p>Compare every claim with your source. Preserve uncertainty, check permissions, and make the summary no stronger than the article.</p><p><a href="/guides/review/" target="_blank" rel="noopener">Open the review checklist (new tab)</a></p><button id="clear" type="button" class="secondary">Clear this writing desk</button>
<p class="small">Do not enter passwords or sensitive material. <a href="/privacy/" target="_blank" rel="noopener">Data use (new tab)</a></p></aside></div>`, script: '/desk.js'
  },
  {
    route: '/help/local-workspace/', title: 'Save and restore your writing', description: 'Learn how to use the local writing desk and distinguish a private workspace backup from a reviewed Markdown article export.',
    body: `<header class="page-intro"><p class="eyebrow">Workspace help</p><h1>Keep unfinished work without creating an account.</h1><p class="lead">The local writing desk works without AI activation. You can also use private backups in the invitation-only pilot once you have access.</p></header>
<h2>Three different ways to work</h2><p><a href="/write/">Local writing desk:</a> write or paste your own article. No AI generates or rewrites it. <a href="/demo/">Sample editor:</a> practice with prewritten fictional examples. <a href="/pilot">Private pilot:</a> invited users can request an AI draft only after the owner completes activation. These are separate capabilities.</p>
<h2>Article export or private backup?</h2><dl><dt>Article Markdown (.md)</dt><dd>Your reviewed title, excerpt, description, draft flag, and body. It omits source notes and review questions. Exporting does not publish anything. Check how your website handles the metadata and title.</dd><dt>Private workspace backup (.json)</dt><dd>Your notes, audience, purpose, article type, all draft fields, and review questions. It can preserve an unfinished article that is not ready for export. It does not include application sign-in fields, AI consent, or review approval. It is unencrypted and may contain private writing.</dd></dl>
<h2>Save before leaving</h2><ol><li>Open Save or restore this workspace. Read and acknowledge what the backup contains.</li><li>Select Download private backup. Check your device's downloads or files app and confirm that a file with a name starting <code>drafttopage-private-workspace-</code> was saved.</li><li>Keep the file in your own private storage. Do not publish it, place it in a public repository, or attach it to a public issue. Backup filenames do not include your article title.</li></ol><p>A download request is not proof that your device saved the file. There is no autosave, account history, or server recovery. Browser exit warnings are not reliable protection, especially when switching apps or closing a mobile browser.</p>
<h2>Resume from a backup</h2><ol><li>Open the local writing desk, or sign in to the private pilot when available.</li><li>Choose Restore a Draft to Page backup and select your workspace JSON file, up to 128 KiB.</li><li>The page validates the entire file before asking to replace existing writing. Cancel to keep the current workspace. Invalid files leave current work unchanged.</li><li>Review the restored material. Any prior review approval is cleared, and pilot AI consent must be given again. Restoring never calls AI, uploads the file, or publishes anything.</li></ol><p>Workspace files use the same format in the local desk and pilot. A plain Markdown file is not a workspace backup. To edit ordinary Markdown, paste its article body into the desk and enter the page details separately. Unknown backup versions and unexpected fields are rejected rather than silently discarded.</p>
<h2>Use the preview as a reading aid</h2><p>The desk's preview supports paragraphs, standalone headings, and simple lists. It deliberately does not execute HTML, open links, or load images. Inline formatting may remain visible as Markdown. Your actual website may render the article differently, so use a nonpublic destination preview before publishing.</p>
<h2>Common problems</h2><p><strong>Export is disabled:</strong> review the article and check the approval box. Editing clears it. Complete the required article fields and use a valid filename.</p><p><strong>The clipboard is blocked:</strong> download Markdown or manually select and copy the text.</p><p><strong>A backup is rejected:</strong> check that it is a Draft to Page workspace JSON file and is within the size limit. Do not shorten or alter it blindly. Your current writing is still in the open tab.</p><p><strong>You left without a file:</strong> there is no guaranteed way to recover discarded writing. Check your own original document or downloads, not an assumed account history.</p>
<p><a class="button" href="/write/">Open the local writing desk</a></p>`
  }
];
